steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'OSM_URL=$_OSM_URL'
  - '-t'
  - '$_IMAGE'
  - '.'
images:
- '$_IMAGE'
options:
  machineType: 'E2_HIGHCPU_32'
timeout: '3600s'
